version: '3.8'
services:
  nodetsdb:
    container_name: nodetsdb
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Letmein!
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    expose:
      - '5432'
    networks:
      - nodetsnet

networks:
  nodetsnet:
